name: Deploy to AWS Server

on:
  push:
    branches:
      - main # Workflow berjalan saat ada perubahan di branch `main`

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to server
        env:
          TARGET_SERVER: "ubuntu@54.169.122.92" # Ganti dengan alamat server atau DNS publik
          TARGET_DIRECTORY: "/home/ubuntu/coba" # Direktori tempat aplikasi Anda di server
        run: |
          ssh -o StrictHostKeyChecking=no $TARGET_SERVER << 'EOF'
            cd $TARGET_DIRECTORY
            git remote set-url origin git@github.com:kevinvinn/coba.git  # Gunakan SSH untuk mengakses GitHub
            git pull origin main  # Menarik perubahan terbaru dari repository
            npm install  # Install dependencies baru jika ada
            pm2 start app.js --name "my-app" || pm2 restart all  # Menjalankan aplikasi menggunakan PM2 atau restart jika sudah berjalan
          EOF
