name: Deploy to EC2

on:
  push:
    branches:
      - main # Jalankan aksi ini ketika ada perubahan di branch main

jobs:
  deploy:
    runs-on: ubuntu-latest # Menggunakan runner ubuntu

    steps:
      - name: Checkout code from GitHub
        uses: actions/checkout@v3 # Mengambil kode dari repository GitHub

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3 # Setup SSH Agent untuk menggunakan private key
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }} # Menggunakan SSH key yang disimpan di GitHub Secrets

      - name: SSH to EC2 and deploy
        run: |
          # Pastikan tidak ada masalah verifikasi host
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} ubuntu@$TARGET_SERVER << 'EOF'
            # Arahkan ke direktori aplikasi
            cd $TARGET_DIRECTORY || { echo "Gagal pindah ke direktori aplikasi"; exit 1; }

            # Lakukan git pull untuk menarik pembaruan terbaru
            git remote set-url origin git@github.com:kevinvinn/coba.git  # Pastikan menggunakan SSH untuk GitHub
            git pull origin main || { echo "Git pull gagal"; exit 1; }

            # Install dependencies jika ada perubahan
            npm install || { echo "npm install gagal"; exit 1; }

            # Restart aplikasi dengan PM2
            pm2 restart my-app || { echo "Gagal restart PM2"; exit 1; }
          EOF
