name: Deploy to AWS Server

on:
  push:
    branches:
      - main # Workflow berjalan saat ada perubahan di branch `main`

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to server
        env:
          TARGET_SERVER: "ubuntu@ec2-54-169-122-92.ap-southeast-1.compute.amazonaws.com" # atau gunakan DNS publik server Anda
          TARGET_DIRECTORY: "/home/ubuntu/coba" # Direktori tempat aplikasi Anda berada di server
        run: |
          ssh -o StrictHostKeyChecking=no $TARGET_SERVER << 'EOF'
            cd $TARGET_DIRECTORY
            git pull origin main
            npm install  # Install dependencies baru jika ada
            pm2 restart all  # Restart aplikasi yang dikelola oleh PM2
          EOF
