name: Deploy to EC2

on:
  push:
    branches:
      - main # Atur sesuai dengan nama branch yang Anda gunakan

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add GitHub SSH Key to known hosts
        run: |
          # Menambahkan host key GitHub untuk memastikan tidak ada error saat SSH
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: SSH to EC2 and deploy
  run: |
    # Memastikan koneksi SSH tidak meminta verifikasi
    ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} ubuntu@$TARGET_SERVER << 'EOF'
      # Masuk ke direktori aplikasi
      cd $TARGET_DIRECTORY
      echo "Menarik perubahan terbaru dari GitHub..."
      git remote set-url origin git@github.com:kevinvinn/coba.git  # Gunakan SSH untuk mengakses GitHub
      git pull origin main || { echo "Git pull gagal"; exit 1; }  # Pastikan git pull berhasil
      echo "Instalasi dependensi..."
      npm install  # Install dependencies baru jika ada
      echo "Menjalankan PM2..."
      pm2 restart my-app  # Restart aplikasi dengan PM2
    EOF


      - name: Clean up SSH agent
        run: ssh-agent -k
